// eslint-disable-next-line
export const LIST_ACTIONS = {
    SHIP_PLACING_TOGGLE: 'SHIP_PLACING_TOOGLE',
    BATTLE_READY: 'BATTLE_READY',
    SHIP_SELECT: 'SHIP_SELECT',
    SHIP_SETUP: 'SHIP_SETUP',
    OPPONENT_WAITING: 'OPPONENT_WAITING',
    GAME_START: 'GAME_START'
};

export const SOCKET_ACTIONS = {
    GAME_START: 'GAME_START',
    USER_JOIN: 'USER_JOIN',
    USER_SHOOT: 'USER_SHOOT',
    USER_LEFT: 'USER_LEFT',
    CELL_HIT: 'CELL_HIT',
};
